/////////////////////////////////////////////////////////
// author: Andrei Militaru 
// date: 21st of May 2019 
// Script automatically generated by https://git.ee.ethz.ch/andreimi/boltzmann_redpitaya/tree/master/python_scripts/write_argv_delay_module.py
/////////////////////////////////////////////////////////

module delay_max256clocks (
	input wire [15:0] data_i,
	input wire [7:0] sel_i,
	input wire clk_i,
	input wire rst_i,
	input wire [15:0] data_o,
	);

	wire [15:0] data0;
	wire [15:0] data1;
	wire [15:0] data2;
	wire [15:0] data3;
	wire [15:0] data4;
	wire [15:0] data5;
	wire [15:0] data6;
	wire [15:0] data7;
	wire [15:0] data8;
	wire [15:0] data9;
	wire [15:0] data10;
	wire [15:0] data11;
	wire [15:0] data12;
	wire [15:0] data13;
	wire [15:0] data14;
	wire [15:0] data15;
	wire [15:0] data16;
	wire [15:0] data17;
	wire [15:0] data18;
	wire [15:0] data19;
	wire [15:0] data20;
	wire [15:0] data21;
	wire [15:0] data22;
	wire [15:0] data23;
	wire [15:0] data24;
	wire [15:0] data25;
	wire [15:0] data26;
	wire [15:0] data27;
	wire [15:0] data28;
	wire [15:0] data29;
	wire [15:0] data30;
	wire [15:0] data31;
	wire [15:0] data32;
	wire [15:0] data33;
	wire [15:0] data34;
	wire [15:0] data35;
	wire [15:0] data36;
	wire [15:0] data37;
	wire [15:0] data38;
	wire [15:0] data39;
	wire [15:0] data40;
	wire [15:0] data41;
	wire [15:0] data42;
	wire [15:0] data43;
	wire [15:0] data44;
	wire [15:0] data45;
	wire [15:0] data46;
	wire [15:0] data47;
	wire [15:0] data48;
	wire [15:0] data49;
	wire [15:0] data50;
	wire [15:0] data51;
	wire [15:0] data52;
	wire [15:0] data53;
	wire [15:0] data54;
	wire [15:0] data55;
	wire [15:0] data56;
	wire [15:0] data57;
	wire [15:0] data58;
	wire [15:0] data59;
	wire [15:0] data60;
	wire [15:0] data61;
	wire [15:0] data62;
	wire [15:0] data63;
	wire [15:0] data64;
	wire [15:0] data65;
	wire [15:0] data66;
	wire [15:0] data67;
	wire [15:0] data68;
	wire [15:0] data69;
	wire [15:0] data70;
	wire [15:0] data71;
	wire [15:0] data72;
	wire [15:0] data73;
	wire [15:0] data74;
	wire [15:0] data75;
	wire [15:0] data76;
	wire [15:0] data77;
	wire [15:0] data78;
	wire [15:0] data79;
	wire [15:0] data80;
	wire [15:0] data81;
	wire [15:0] data82;
	wire [15:0] data83;
	wire [15:0] data84;
	wire [15:0] data85;
	wire [15:0] data86;
	wire [15:0] data87;
	wire [15:0] data88;
	wire [15:0] data89;
	wire [15:0] data90;
	wire [15:0] data91;
	wire [15:0] data92;
	wire [15:0] data93;
	wire [15:0] data94;
	wire [15:0] data95;
	wire [15:0] data96;
	wire [15:0] data97;
	wire [15:0] data98;
	wire [15:0] data99;
	wire [15:0] data100;
	wire [15:0] data101;
	wire [15:0] data102;
	wire [15:0] data103;
	wire [15:0] data104;
	wire [15:0] data105;
	wire [15:0] data106;
	wire [15:0] data107;
	wire [15:0] data108;
	wire [15:0] data109;
	wire [15:0] data110;
	wire [15:0] data111;
	wire [15:0] data112;
	wire [15:0] data113;
	wire [15:0] data114;
	wire [15:0] data115;
	wire [15:0] data116;
	wire [15:0] data117;
	wire [15:0] data118;
	wire [15:0] data119;
	wire [15:0] data120;
	wire [15:0] data121;
	wire [15:0] data122;
	wire [15:0] data123;
	wire [15:0] data124;
	wire [15:0] data125;
	wire [15:0] data126;
	wire [15:0] data127;
	wire [15:0] data128;
	wire [15:0] data129;
	wire [15:0] data130;
	wire [15:0] data131;
	wire [15:0] data132;
	wire [15:0] data133;
	wire [15:0] data134;
	wire [15:0] data135;
	wire [15:0] data136;
	wire [15:0] data137;
	wire [15:0] data138;
	wire [15:0] data139;
	wire [15:0] data140;
	wire [15:0] data141;
	wire [15:0] data142;
	wire [15:0] data143;
	wire [15:0] data144;
	wire [15:0] data145;
	wire [15:0] data146;
	wire [15:0] data147;
	wire [15:0] data148;
	wire [15:0] data149;
	wire [15:0] data150;
	wire [15:0] data151;
	wire [15:0] data152;
	wire [15:0] data153;
	wire [15:0] data154;
	wire [15:0] data155;
	wire [15:0] data156;
	wire [15:0] data157;
	wire [15:0] data158;
	wire [15:0] data159;
	wire [15:0] data160;
	wire [15:0] data161;
	wire [15:0] data162;
	wire [15:0] data163;
	wire [15:0] data164;
	wire [15:0] data165;
	wire [15:0] data166;
	wire [15:0] data167;
	wire [15:0] data168;
	wire [15:0] data169;
	wire [15:0] data170;
	wire [15:0] data171;
	wire [15:0] data172;
	wire [15:0] data173;
	wire [15:0] data174;
	wire [15:0] data175;
	wire [15:0] data176;
	wire [15:0] data177;
	wire [15:0] data178;
	wire [15:0] data179;
	wire [15:0] data180;
	wire [15:0] data181;
	wire [15:0] data182;
	wire [15:0] data183;
	wire [15:0] data184;
	wire [15:0] data185;
	wire [15:0] data186;
	wire [15:0] data187;
	wire [15:0] data188;
	wire [15:0] data189;
	wire [15:0] data190;
	wire [15:0] data191;
	wire [15:0] data192;
	wire [15:0] data193;
	wire [15:0] data194;
	wire [15:0] data195;
	wire [15:0] data196;
	wire [15:0] data197;
	wire [15:0] data198;
	wire [15:0] data199;
	wire [15:0] data200;
	wire [15:0] data201;
	wire [15:0] data202;
	wire [15:0] data203;
	wire [15:0] data204;
	wire [15:0] data205;
	wire [15:0] data206;
	wire [15:0] data207;
	wire [15:0] data208;
	wire [15:0] data209;
	wire [15:0] data210;
	wire [15:0] data211;
	wire [15:0] data212;
	wire [15:0] data213;
	wire [15:0] data214;
	wire [15:0] data215;
	wire [15:0] data216;
	wire [15:0] data217;
	wire [15:0] data218;
	wire [15:0] data219;
	wire [15:0] data220;
	wire [15:0] data221;
	wire [15:0] data222;
	wire [15:0] data223;
	wire [15:0] data224;
	wire [15:0] data225;
	wire [15:0] data226;
	wire [15:0] data227;
	wire [15:0] data228;
	wire [15:0] data229;
	wire [15:0] data230;
	wire [15:0] data231;
	wire [15:0] data232;
	wire [15:0] data233;
	wire [15:0] data234;
	wire [15:0] data235;
	wire [15:0] data236;
	wire [15:0] data237;
	wire [15:0] data238;
	wire [15:0] data239;
	wire [15:0] data240;
	wire [15:0] data241;
	wire [15:0] data242;
	wire [15:0] data243;
	wire [15:0] data244;
	wire [15:0] data245;
	wire [15:0] data246;
	wire [15:0] data247;
	wire [15:0] data248;
	wire [15:0] data249;
	wire [15:0] data250;
	wire [15:0] data251;
	wire [15:0] data252;
	wire [15:0] data253;
	wire [15:0] data254;
	wire [15:0] data255;

	shift_register_256delays shift_register_256delays_i (
				.clk_i(clk_i),
				.rst_i(rst_i),
				.data_i(data_i),
				.data0_o(data0),
				.data1_o(data1),
				.data2_o(data2),
				.data3_o(data3),
				.data4_o(data4),
				.data5_o(data5),
				.data6_o(data6),
				.data7_o(data7),
				.data8_o(data8),
				.data9_o(data9),
				.data10_o(data10),
				.data11_o(data11),
				.data12_o(data12),
				.data13_o(data13),
				.data14_o(data14),
				.data15_o(data15),
				.data16_o(data16),
				.data17_o(data17),
				.data18_o(data18),
				.data19_o(data19),
				.data20_o(data20),
				.data21_o(data21),
				.data22_o(data22),
				.data23_o(data23),
				.data24_o(data24),
				.data25_o(data25),
				.data26_o(data26),
				.data27_o(data27),
				.data28_o(data28),
				.data29_o(data29),
				.data30_o(data30),
				.data31_o(data31),
				.data32_o(data32),
				.data33_o(data33),
				.data34_o(data34),
				.data35_o(data35),
				.data36_o(data36),
				.data37_o(data37),
				.data38_o(data38),
				.data39_o(data39),
				.data40_o(data40),
				.data41_o(data41),
				.data42_o(data42),
				.data43_o(data43),
				.data44_o(data44),
				.data45_o(data45),
				.data46_o(data46),
				.data47_o(data47),
				.data48_o(data48),
				.data49_o(data49),
				.data50_o(data50),
				.data51_o(data51),
				.data52_o(data52),
				.data53_o(data53),
				.data54_o(data54),
				.data55_o(data55),
				.data56_o(data56),
				.data57_o(data57),
				.data58_o(data58),
				.data59_o(data59),
				.data60_o(data60),
				.data61_o(data61),
				.data62_o(data62),
				.data63_o(data63),
				.data64_o(data64),
				.data65_o(data65),
				.data66_o(data66),
				.data67_o(data67),
				.data68_o(data68),
				.data69_o(data69),
				.data70_o(data70),
				.data71_o(data71),
				.data72_o(data72),
				.data73_o(data73),
				.data74_o(data74),
				.data75_o(data75),
				.data76_o(data76),
				.data77_o(data77),
				.data78_o(data78),
				.data79_o(data79),
				.data80_o(data80),
				.data81_o(data81),
				.data82_o(data82),
				.data83_o(data83),
				.data84_o(data84),
				.data85_o(data85),
				.data86_o(data86),
				.data87_o(data87),
				.data88_o(data88),
				.data89_o(data89),
				.data90_o(data90),
				.data91_o(data91),
				.data92_o(data92),
				.data93_o(data93),
				.data94_o(data94),
				.data95_o(data95),
				.data96_o(data96),
				.data97_o(data97),
				.data98_o(data98),
				.data99_o(data99),
				.data100_o(data100),
				.data101_o(data101),
				.data102_o(data102),
				.data103_o(data103),
				.data104_o(data104),
				.data105_o(data105),
				.data106_o(data106),
				.data107_o(data107),
				.data108_o(data108),
				.data109_o(data109),
				.data110_o(data110),
				.data111_o(data111),
				.data112_o(data112),
				.data113_o(data113),
				.data114_o(data114),
				.data115_o(data115),
				.data116_o(data116),
				.data117_o(data117),
				.data118_o(data118),
				.data119_o(data119),
				.data120_o(data120),
				.data121_o(data121),
				.data122_o(data122),
				.data123_o(data123),
				.data124_o(data124),
				.data125_o(data125),
				.data126_o(data126),
				.data127_o(data127),
				.data128_o(data128),
				.data129_o(data129),
				.data130_o(data130),
				.data131_o(data131),
				.data132_o(data132),
				.data133_o(data133),
				.data134_o(data134),
				.data135_o(data135),
				.data136_o(data136),
				.data137_o(data137),
				.data138_o(data138),
				.data139_o(data139),
				.data140_o(data140),
				.data141_o(data141),
				.data142_o(data142),
				.data143_o(data143),
				.data144_o(data144),
				.data145_o(data145),
				.data146_o(data146),
				.data147_o(data147),
				.data148_o(data148),
				.data149_o(data149),
				.data150_o(data150),
				.data151_o(data151),
				.data152_o(data152),
				.data153_o(data153),
				.data154_o(data154),
				.data155_o(data155),
				.data156_o(data156),
				.data157_o(data157),
				.data158_o(data158),
				.data159_o(data159),
				.data160_o(data160),
				.data161_o(data161),
				.data162_o(data162),
				.data163_o(data163),
				.data164_o(data164),
				.data165_o(data165),
				.data166_o(data166),
				.data167_o(data167),
				.data168_o(data168),
				.data169_o(data169),
				.data170_o(data170),
				.data171_o(data171),
				.data172_o(data172),
				.data173_o(data173),
				.data174_o(data174),
				.data175_o(data175),
				.data176_o(data176),
				.data177_o(data177),
				.data178_o(data178),
				.data179_o(data179),
				.data180_o(data180),
				.data181_o(data181),
				.data182_o(data182),
				.data183_o(data183),
				.data184_o(data184),
				.data185_o(data185),
				.data186_o(data186),
				.data187_o(data187),
				.data188_o(data188),
				.data189_o(data189),
				.data190_o(data190),
				.data191_o(data191),
				.data192_o(data192),
				.data193_o(data193),
				.data194_o(data194),
				.data195_o(data195),
				.data196_o(data196),
				.data197_o(data197),
				.data198_o(data198),
				.data199_o(data199),
				.data200_o(data200),
				.data201_o(data201),
				.data202_o(data202),
				.data203_o(data203),
				.data204_o(data204),
				.data205_o(data205),
				.data206_o(data206),
				.data207_o(data207),
				.data208_o(data208),
				.data209_o(data209),
				.data210_o(data210),
				.data211_o(data211),
				.data212_o(data212),
				.data213_o(data213),
				.data214_o(data214),
				.data215_o(data215),
				.data216_o(data216),
				.data217_o(data217),
				.data218_o(data218),
				.data219_o(data219),
				.data220_o(data220),
				.data221_o(data221),
				.data222_o(data222),
				.data223_o(data223),
				.data224_o(data224),
				.data225_o(data225),
				.data226_o(data226),
				.data227_o(data227),
				.data228_o(data228),
				.data229_o(data229),
				.data230_o(data230),
				.data231_o(data231),
				.data232_o(data232),
				.data233_o(data233),
				.data234_o(data234),
				.data235_o(data235),
				.data236_o(data236),
				.data237_o(data237),
				.data238_o(data238),
				.data239_o(data239),
				.data240_o(data240),
				.data241_o(data241),
				.data242_o(data242),
				.data243_o(data243),
				.data244_o(data244),
				.data245_o(data245),
				.data246_o(data246),
				.data247_o(data247),
				.data248_o(data248),
				.data249_o(data249),
				.data250_o(data250),
				.data251_o(data251),
				.data252_o(data252),
				.data253_o(data253),
				.data254_o(data254),
				.data255_o(data255)
	);

	MUX_8bits MUX_8bits_i (
				.clk_i(clk_i),
				.rst_i(rst_i),
				.sel_i(sel_i),
				.data0_i(data0),
				.data1_i(data1),
				.data2_i(data2),
				.data3_i(data3),
				.data4_i(data4),
				.data5_i(data5),
				.data6_i(data6),
				.data7_i(data7),
				.data8_i(data8),
				.data9_i(data9),
				.data10_i(data10),
				.data11_i(data11),
				.data12_i(data12),
				.data13_i(data13),
				.data14_i(data14),
				.data15_i(data15),
				.data16_i(data16),
				.data17_i(data17),
				.data18_i(data18),
				.data19_i(data19),
				.data20_i(data20),
				.data21_i(data21),
				.data22_i(data22),
				.data23_i(data23),
				.data24_i(data24),
				.data25_i(data25),
				.data26_i(data26),
				.data27_i(data27),
				.data28_i(data28),
				.data29_i(data29),
				.data30_i(data30),
				.data31_i(data31),
				.data32_i(data32),
				.data33_i(data33),
				.data34_i(data34),
				.data35_i(data35),
				.data36_i(data36),
				.data37_i(data37),
				.data38_i(data38),
				.data39_i(data39),
				.data40_i(data40),
				.data41_i(data41),
				.data42_i(data42),
				.data43_i(data43),
				.data44_i(data44),
				.data45_i(data45),
				.data46_i(data46),
				.data47_i(data47),
				.data48_i(data48),
				.data49_i(data49),
				.data50_i(data50),
				.data51_i(data51),
				.data52_i(data52),
				.data53_i(data53),
				.data54_i(data54),
				.data55_i(data55),
				.data56_i(data56),
				.data57_i(data57),
				.data58_i(data58),
				.data59_i(data59),
				.data60_i(data60),
				.data61_i(data61),
				.data62_i(data62),
				.data63_i(data63),
				.data64_i(data64),
				.data65_i(data65),
				.data66_i(data66),
				.data67_i(data67),
				.data68_i(data68),
				.data69_i(data69),
				.data70_i(data70),
				.data71_i(data71),
				.data72_i(data72),
				.data73_i(data73),
				.data74_i(data74),
				.data75_i(data75),
				.data76_i(data76),
				.data77_i(data77),
				.data78_i(data78),
				.data79_i(data79),
				.data80_i(data80),
				.data81_i(data81),
				.data82_i(data82),
				.data83_i(data83),
				.data84_i(data84),
				.data85_i(data85),
				.data86_i(data86),
				.data87_i(data87),
				.data88_i(data88),
				.data89_i(data89),
				.data90_i(data90),
				.data91_i(data91),
				.data92_i(data92),
				.data93_i(data93),
				.data94_i(data94),
				.data95_i(data95),
				.data96_i(data96),
				.data97_i(data97),
				.data98_i(data98),
				.data99_i(data99),
				.data100_i(data100),
				.data101_i(data101),
				.data102_i(data102),
				.data103_i(data103),
				.data104_i(data104),
				.data105_i(data105),
				.data106_i(data106),
				.data107_i(data107),
				.data108_i(data108),
				.data109_i(data109),
				.data110_i(data110),
				.data111_i(data111),
				.data112_i(data112),
				.data113_i(data113),
				.data114_i(data114),
				.data115_i(data115),
				.data116_i(data116),
				.data117_i(data117),
				.data118_i(data118),
				.data119_i(data119),
				.data120_i(data120),
				.data121_i(data121),
				.data122_i(data122),
				.data123_i(data123),
				.data124_i(data124),
				.data125_i(data125),
				.data126_i(data126),
				.data127_i(data127),
				.data128_i(data128),
				.data129_i(data129),
				.data130_i(data130),
				.data131_i(data131),
				.data132_i(data132),
				.data133_i(data133),
				.data134_i(data134),
				.data135_i(data135),
				.data136_i(data136),
				.data137_i(data137),
				.data138_i(data138),
				.data139_i(data139),
				.data140_i(data140),
				.data141_i(data141),
				.data142_i(data142),
				.data143_i(data143),
				.data144_i(data144),
				.data145_i(data145),
				.data146_i(data146),
				.data147_i(data147),
				.data148_i(data148),
				.data149_i(data149),
				.data150_i(data150),
				.data151_i(data151),
				.data152_i(data152),
				.data153_i(data153),
				.data154_i(data154),
				.data155_i(data155),
				.data156_i(data156),
				.data157_i(data157),
				.data158_i(data158),
				.data159_i(data159),
				.data160_i(data160),
				.data161_i(data161),
				.data162_i(data162),
				.data163_i(data163),
				.data164_i(data164),
				.data165_i(data165),
				.data166_i(data166),
				.data167_i(data167),
				.data168_i(data168),
				.data169_i(data169),
				.data170_i(data170),
				.data171_i(data171),
				.data172_i(data172),
				.data173_i(data173),
				.data174_i(data174),
				.data175_i(data175),
				.data176_i(data176),
				.data177_i(data177),
				.data178_i(data178),
				.data179_i(data179),
				.data180_i(data180),
				.data181_i(data181),
				.data182_i(data182),
				.data183_i(data183),
				.data184_i(data184),
				.data185_i(data185),
				.data186_i(data186),
				.data187_i(data187),
				.data188_i(data188),
				.data189_i(data189),
				.data190_i(data190),
				.data191_i(data191),
				.data192_i(data192),
				.data193_i(data193),
				.data194_i(data194),
				.data195_i(data195),
				.data196_i(data196),
				.data197_i(data197),
				.data198_i(data198),
				.data199_i(data199),
				.data200_i(data200),
				.data201_i(data201),
				.data202_i(data202),
				.data203_i(data203),
				.data204_i(data204),
				.data205_i(data205),
				.data206_i(data206),
				.data207_i(data207),
				.data208_i(data208),
				.data209_i(data209),
				.data210_i(data210),
				.data211_i(data211),
				.data212_i(data212),
				.data213_i(data213),
				.data214_i(data214),
				.data215_i(data215),
				.data216_i(data216),
				.data217_i(data217),
				.data218_i(data218),
				.data219_i(data219),
				.data220_i(data220),
				.data221_i(data221),
				.data222_i(data222),
				.data223_i(data223),
				.data224_i(data224),
				.data225_i(data225),
				.data226_i(data226),
				.data227_i(data227),
				.data228_i(data228),
				.data229_i(data229),
				.data230_i(data230),
				.data231_i(data231),
				.data232_i(data232),
				.data233_i(data233),
				.data234_i(data234),
				.data235_i(data235),
				.data236_i(data236),
				.data237_i(data237),
				.data238_i(data238),
				.data239_i(data239),
				.data240_i(data240),
				.data241_i(data241),
				.data242_i(data242),
				.data243_i(data243),
				.data244_i(data244),
				.data245_i(data245),
				.data246_i(data246),
				.data247_i(data247),
				.data248_i(data248),
				.data249_i(data249),
				.data250_i(data250),
				.data251_i(data251),
				.data252_i(data252),
				.data253_i(data253),
				.data254_i(data254),
				.data255_i(data255),
				.data_o(data_o)
	);

endmodule
