#
# Vivado (TM) v2017.2 (64-bit)
#
# create_block_design_sqrt.tcl: Tcl script for re-creating project 'redpitaya_sqrt'
#
# Generated by Vivado on Tue Nov 27 16:01:54 +0100 2018
# IP Build 1909766 on Thu Jun 15 19:58:00 MDT 2017
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (create_block_design_sqrt.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/red-pitaya/redpitayapll/vhdl/sum_limit.vhd"
#    "C:/red-pitaya/redpitayapll/vhdl/pid_w_range.vhd"
#    "C:/red-pitaya/redpitayapll/vhdl/freq_div.vhd"
#    "C:/red-pitaya/redpitayapll/vhdl/nco_driver_2.vhd"
#    "C:/red-pitaya/redpitayapll/vhdl/sincos_lut.vhd"
#    "C:/red-pitaya/redpitayapll/vhdl/waveform_gen.vhd"
#    "C:/red-pitaya/redpitayapll/vhdl/weight_sum.vhd"
#    "C:/red-pitaya/redpitayapll/vhdl/dec_filter.vhd"
#    "C:/red-pitaya/redpitayapll/vhdl/exp_avg_filter.vhd"
#    "C:/red-pitaya/redpitayapll/vhdl/exp_avg_filter_order.vhd"
#    "C:/red-pitaya/redpitayapll/vhdl/mult_n_1.vhd"
#    "C:/red-pitaya/redpitayapll/cores/axis_red_pitaya_dac_v1_0/axis_red_pitaya_dac.v"
#    "C:/red-pitaya/redpitayapll/vhdl/dac_out_switch.vhd"
#    "C:/red-pitaya/redpitayapll/cores/axis_red_pitaya_adc_v1_0/clock_div_dec_filter.vhd"
#    "C:/red-pitaya/redpitayapll/cores/axis_red_pitaya_adc_v1_0/axis_red_pitaya_adc.vhd"
#    "C:/red-pitaya/redpitayapll/tmp/redpitaya_sqrt/redpitaya_sqrt.srcs/sources_1/bd/system/system.bd"
#    "c:/red-pitaya/redpitayapll/tmp/redpitaya_sqrt/redpitaya_sqrt.srcs/sources_1/bd/system/hdl/system_wrapper.v"
#    "C:/red-pitaya/redpitayapll/vhdl/fix_div.vhd"
#    "C:/red-pitaya/redpitayapll/cfg/clocks.xdc"
#    "C:/red-pitaya/redpitayapll/cfg/ports.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "create_block_design_sqrt.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../tmp/redpitaya_sqrt"]"

# Create project
create_project redpitaya_sqrt ./redpitaya_sqrt -part xc7z010clg400-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects redpitaya_sqrt]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/redpitaya_sqrt.cache/ip" -objects $obj
set_property -name "part" -value "xc7z010clg400-1" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../vhdl/sum_limit.vhd"]"\
 "[file normalize "$origin_dir/../vhdl/pid_w_range.vhd"]"\
 "[file normalize "$origin_dir/../vhdl/freq_div.vhd"]"\
 "[file normalize "$origin_dir/../vhdl/nco_driver_2.vhd"]"\
 "[file normalize "$origin_dir/../vhdl/sincos_lut.vhd"]"\
 "[file normalize "$origin_dir/../vhdl/waveform_gen.vhd"]"\
 "[file normalize "$origin_dir/../vhdl/weight_sum.vhd"]"\
 "[file normalize "$origin_dir/../vhdl/dec_filter.vhd"]"\
 "[file normalize "$origin_dir/../vhdl/exp_avg_filter.vhd"]"\
 "[file normalize "$origin_dir/../vhdl/exp_avg_filter_order.vhd"]"\
 "[file normalize "$origin_dir/../vhdl/mult_n_1.vhd"]"\
 "[file normalize "$origin_dir/../cores/axis_red_pitaya_dac_v1_0/axis_red_pitaya_dac.v"]"\
 "[file normalize "$origin_dir/../vhdl/dac_out_switch.vhd"]"\
 "[file normalize "$origin_dir/../cores/axis_red_pitaya_adc_v1_0/clock_div_dec_filter.vhd"]"\
 "[file normalize "$origin_dir/../cores/axis_red_pitaya_adc_v1_0/axis_red_pitaya_adc.vhd"]"\
 "[file normalize "$origin_dir/../tmp/redpitaya_sqrt/redpitaya_sqrt.srcs/sources_1/bd/system/system.bd"]"\
 "[file normalize "$origin_dir/../tmp/redpitaya_sqrt/redpitaya_sqrt.srcs/sources_1/bd/system/hdl/system_wrapper.v"]"\
 "[file normalize "$origin_dir/../vhdl/fix_div.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../vhdl/sum_limit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../vhdl/pid_w_range.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../vhdl/freq_div.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../vhdl/nco_driver_2.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../vhdl/sincos_lut.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../vhdl/waveform_gen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../vhdl/weight_sum.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../vhdl/dec_filter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../vhdl/exp_avg_filter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../vhdl/exp_avg_filter_order.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../vhdl/mult_n_1.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../vhdl/dac_out_switch.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../cores/axis_red_pitaya_adc_v1_0/clock_div_dec_filter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../cores/axis_red_pitaya_adc_v1_0/axis_red_pitaya_adc.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../vhdl/fix_div.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "system_wrapper" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../cfg/clocks.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../cfg/clocks.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../cfg/ports.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../cfg/ports.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7z010clg400-1 -flow {Vivado Synthesis 2017} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2017" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7z010clg400-1" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7z010clg400-1 -flow {Vivado Implementation 2017} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2017" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7z010clg400-1" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:redpitaya_sqrt"
